[package]
name = "ruslin-data-uniffi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
name = "uniffi_ruslin"

[dependencies]
uniffi = "0.22.0"
uniffi_macros = "0.22.0"
ruslin-data = { path = "./ruslin-data" }
openssl-sys = "0.9.79"
openssl = { version = "0.10.44", features = ["vendored"] }
log = "0.4.17"
android_logger = "=0.11.1"
tokio = { version = "1.23.0", features = ["full"] }
libsqlite3-sys = { version = "0.25.2", features = ["bundled"] }

[build-dependencies]
uniffi_build = { version = "0.22.0", features=["builtin-bindgen"] }

[profile.release]
lto = true
